
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release src/DotnetDacMigration
    - name: Publish package
      run: dotnet nuget push src/DotnetDacMigration/nupkg/*.nupkg -s https://api.nuget.org/v3/index.json
      if: ${{ github.ref == 'refs/heads/main' }}
    
